version: '3'
services:
  web:
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
      - ./app:/app  # Mount your project directory into the container

  curl-container:
    image: lwthiker/curl-impersonate:0.5-chrome
    command: ["sleep", "infinity"]  # Keep the container running
